"""Type stubs for the compiled extension module ``rvsim._core``."""

from typing import Any, Callable, Iterator, Optional, Union

from typing_extensions import Self

def version() -> str: ...
def disassemble(inst: int) -> str: ...

class Instruction:
    """One retired instruction, returned by :meth:`Simulator.step`."""

    @property
    def pc(self) -> int: ...
    @property
    def raw(self) -> int: ...
    @property
    def asm(self) -> str: ...
    @property
    def cycles(self) -> int: ...

class QueryResult:
    """``(path, value)`` pairs a wildcard :meth:`Stats.query` matched."""

    def sum(self) -> float: ...
    def __len__(self) -> int: ...
    def is_empty(self) -> bool: ...
    def __iter__(self) -> Iterator[tuple[str, float]]: ...
    def by_subject(self) -> dict[str, float]: ...
    def paths(self) -> list[str]: ...

class Stats:
    """The simulator's hierarchical statistics tree."""

    @property
    def cycles(self) -> int: ...
    @property
    def instructions_retired(self) -> int: ...
    @property
    def ipc(self) -> float: ...
    @property
    def cpi(self) -> float: ...
    def get(self, path: str, default: Optional[float] = None) -> Optional[float]: ...
    def __getitem__(self, path: str) -> float: ...
    def __contains__(self, path: str) -> bool: ...
    def query(self, pattern: str) -> QueryResult: ...
    def summary(self, sections: Optional[list[str]] = None) -> str: ...
    def subjects(self) -> list[str]: ...

class PipelineSnapshot:
    """Point-in-time contents of every inter-stage latch; each stage is a
    list of slot dicts (length at most ``width``)."""

    @property
    def width(self) -> int: ...
    @property
    def fetch1_fetch2(self) -> list[dict[str, Any]]: ...
    @property
    def fetch2_decode(self) -> list[dict[str, Any]]: ...
    @property
    def decode_rename(self) -> list[dict[str, Any]]: ...
    @property
    def rename_issue(self) -> list[dict[str, Any]]: ...
    @property
    def issue_queue(self) -> list[dict[str, Any]]: ...
    @property
    def execute_mem1(self) -> list[dict[str, Any]]: ...
    @property
    def mem1_mem2(self) -> list[dict[str, Any]]: ...
    @property
    def mem2_wb(self) -> list[dict[str, Any]]: ...
    def render(self) -> str: ...
    def visualize(self) -> None: ...

class Registers:
    """A hart's integer registers, indexed 0-31."""

    def __getitem__(self, idx: int) -> int: ...
    def __setitem__(self, idx: int, value: int) -> None: ...

class Csrs:
    """A hart's CSRs, indexed by address or lower-case name."""

    def __getitem__(self, key: Union[int, str]) -> int: ...

class Hart:
    @property
    def id(self) -> int: ...
    @property
    def pc(self) -> int:
        """The architectural PC: the next instruction to retire."""
    @pc.setter
    def pc(self, value: int) -> None: ...
    @property
    def privilege(self) -> str: ...
    @property
    def instructions_retired(self) -> int: ...
    @property
    def regs(self) -> Registers: ...
    @property
    def csrs(self) -> Csrs: ...

class Harts:
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Hart: ...

class Memory:
    """Physical memory read as 32- or 64-bit words by address."""

    def __getitem__(self, addr: int) -> int: ...

class VirtualMemory:
    """Memory read through hart 0's current translation."""

    def __getitem__(self, addr: int) -> int: ...

class Simulator:
    def __new__(
        cls,
        config_dict: Any,
        *,
        elf_data: Optional[bytes] = None,
        kernel_path: Optional[str] = None,
        dtb_path: Optional[str] = None,
        disk_path: Optional[str] = None,
    ) -> Self: ...
    @property
    def pc(self) -> int:
        """Hart 0's architectural PC; setting it restarts fetch there."""
    @pc.setter
    def pc(self, value: int) -> None: ...
    @property
    def privilege(self) -> str: ...
    @property
    def trace(self) -> bool: ...
    @trace.setter
    def trace(self, value: bool) -> None: ...
    def trace_filter(
        self,
        harts: Optional[list[int]] = None,
        cycles: Optional[tuple[int, int]] = None,
        trap_causes: Optional[list[int]] = None,
    ) -> None: ...
    @property
    def stats(self) -> Stats: ...
    @property
    def regs(self) -> Registers: ...
    @property
    def csrs(self) -> Csrs: ...
    @property
    def harts(self) -> Harts: ...
    @property
    def hart_count(self) -> int: ...
    @property
    def mem32(self) -> Memory: ...
    @property
    def mem64(self) -> Memory: ...
    @property
    def vmem32(self) -> VirtualMemory: ...
    @property
    def vmem64(self) -> VirtualMemory: ...
    @property
    def pc_trace(self) -> list[tuple[int, int]]: ...
    def open_commit_log(self, path: str) -> None: ...
    def step(self, max_cycles: int = 100_000) -> Optional[Instruction]: ...
    def run(
        self,
        limit: Optional[int] = None,
        progress: int = 0,
        stats_sections: Optional[list[str]] = None,
    ) -> Optional[int]: ...
    def sample(self, every: int, limit: Optional[int] = None) -> list[Stats]: ...
    def run_until(
        self,
        predicate: Optional[Callable[["Simulator"], bool]] = None,
        *,
        pc: Optional[int] = None,
        privilege: Optional[str] = None,
        limit: Optional[int] = None,
        chunk: int = 10_000,
    ) -> Optional[int]: ...
    def tick(self) -> None: ...
    def translate(self, vaddr: int) -> int: ...
    def read_phys_bytes(self, paddr: int, length: int) -> bytes: ...
    def pipeline_snapshot(self) -> PipelineSnapshot: ...
    def save(self, path: str) -> None: ...
    def restore(self, path: str) -> None: ...
