"""Type hints for riscv_sim; the Rust backend provides PySystem, PyCpu, and related classes."""

from typing import Optional

class PySystem:
    def __init__(self, config_dict: dict, disk_path: Optional[str] = None) -> None: ...
    def load_binary(self, data: bytes, addr: int) -> None: ...

class CPU:
    def __init__(self, system: PySystem, config_dict: dict) -> None: ...
    def run(self) -> int: ...
    def run_with_limit(self, max_cycles: int) -> Optional[int]: ...
    def get_pc(self) -> int: ...
    def get_stats(self): ...
    def set_pc(self, pc: int) -> None: ...
    def write_register(self, reg: int, value: int) -> None: ...
    def read_register(self, reg: int) -> int: ...
    def set_direct_mode(self, enabled: bool) -> None: ...
